# set buffer size for extract and normalize stages
[data_writer]
buffer_max_items=15000
file_max_items=1000000
file_max_bytes=5000000

# for all sources and resources being extracted
[extract]
workers=11

[normalize]
# use 3 worker processes to process 3 files in parallel
workers=11
file_max_bytes=5000000
data_page_size=5000000

[load]
workers=11

[destination.filesystem]
kwargs = '{"auto_mkdir": true}'
bucket_url='.'

[pipeline] # in ./dlt/config.toml
loader_file_format="parquet"

[workstreams.data_writer]
buffer_max_items=100000
file_max_items=100000

[workstreams.normalize]
# use 3 worker processes to process 3 files in parallel
workers=11
file_max_bytes=500000
data_page_size=500000